// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAIPjkDddXS3SEaXabKyP5XNEo7fciKOY',
    appId: '1:1066766316804:web:1caa0aa75cc47d86cc8c51',
    messagingSenderId: '1066766316804',
    projectId: 'practice-flashchat',
    authDomain: 'practice-flashchat.firebaseapp.com',
    storageBucket: 'practice-flashchat.firebasestorage.app',
    measurementId: 'G-340DN2M52H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCpxC3SES2dqNu2CjfCgz8IfGiqZVmpdI',
    appId: '1:1066766316804:android:3191ebd161f4df2dcc8c51',
    messagingSenderId: '1066766316804',
    projectId: 'practice-flashchat',
    storageBucket: 'practice-flashchat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASnsxuNWCJQSRJOTp8v7DvmRuPAXbm_fk',
    appId: '1:1066766316804:ios:280d99e36b46d641cc8c51',
    messagingSenderId: '1066766316804',
    projectId: 'practice-flashchat',
    storageBucket: 'practice-flashchat.firebasestorage.app',
    iosBundleId: 'com.arpit.practiceflashchat.practiceFlashchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASnsxuNWCJQSRJOTp8v7DvmRuPAXbm_fk',
    appId: '1:1066766316804:ios:280d99e36b46d641cc8c51',
    messagingSenderId: '1066766316804',
    projectId: 'practice-flashchat',
    storageBucket: 'practice-flashchat.firebasestorage.app',
    iosBundleId: 'com.arpit.practiceflashchat.practiceFlashchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAIPjkDddXS3SEaXabKyP5XNEo7fciKOY',
    appId: '1:1066766316804:web:36592585c855ecf8cc8c51',
    messagingSenderId: '1066766316804',
    projectId: 'practice-flashchat',
    authDomain: 'practice-flashchat.firebaseapp.com',
    storageBucket: 'practice-flashchat.firebasestorage.app',
    measurementId: 'G-JQMVP2T205',
  );
}
